# Generated by Django 2.0 on 2018-05-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seguridad',
            new_name='Usuario',
        ),
    ]
